### ISSUE TITLE
stuck on word matching exercise

### ISSUE THREAD

**Issue by mrkcxd** [anonymoushackerIV/Duolingo-Pro-BETA#6]
This happens in certain word matching exercises and you will have to solve them manually before the autosolver can continue working on its own.

**Comment by anonymoushackerIV** [comment]
Which course taken from which language is the problem occurring in? Additionally could you tell me which unit and section (or units/sections) the problem happens in? 

Thanks

**Comment by mrkcxd** [comment]
It seems like this only happens randomly in Path mode and is not specific to any Unit or Course.
